# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 550)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Active_frame = QtWidgets.QFrame(self.centralwidget)
        self.Active_frame.setGeometry(QtCore.QRect(0, 330, 550, 270))
        self.Active_frame.setStyleSheet("background : #D8c3a5")
        self.Active_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Active_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Active_frame.setObjectName("Active_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Active_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 531, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Input_Size = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Input_Size.setMaxLength(2)
        self.Input_Size.setObjectName("Input_Size")
        self.horizontalLayout.addWidget(self.Input_Size)
        self.Lets = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Lets.setObjectName("Lets")
        self.horizontalLayout.addWidget(self.Lets)
        self.Save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Save.setFont(font)
        self.Save.setObjectName("Save")
        self.horizontalLayout.addWidget(self.Save)
        self.Statistic = QtWidgets.QTextEdit(self.Active_frame)
        self.Statistic.setGeometry(QtCore.QRect(-1, 40, 550, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Statistic.setFont(font)
        self.Statistic.setReadOnly(True)
        self.Statistic.setObjectName("Statistic")
        self.Matrix_frame = QtWidgets.QFrame(self.centralwidget)
        self.Matrix_frame.setGeometry(QtCore.QRect(0, 0, 550, 330))
        self.Matrix_frame.setStyleSheet("background : #EAE7DC")
        self.Matrix_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Matrix_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Matrix_frame.setObjectName("Matrix_frame")
        self.Matrix_text = QtWidgets.QTextEdit(self.Matrix_frame)
        self.Matrix_text.setGeometry(QtCore.QRect(0, 0, 551, 331))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Matrix_text.setFont(font)
        self.Matrix_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Matrix_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Matrix_text.setReadOnly(True)
        self.Matrix_text.setCursorWidth(1)
        self.Matrix_text.setPlaceholderText("")
        self.Matrix_text.setObjectName("Matrix_text")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проверка свойств матрицы"))
        self.Lets.setText(_translate("MainWindow", "Calculate"))
        self.Save.setText(_translate("MainWindow", "Save"))
